version: "3.7"

services:
  ImgWebPy:
    image: glcr.iefi.xyz/bhghdhfh/random-photo-return:latest
    restart: unless-stopped
    volumes:
      - ./images:/config/workspace/Random-img-web/img
    ports:
      - 9996:5000